version: '3'


services:
  db:
    image: mysql
    environment:
      MYSQL_USER: gabriel
      MYSQL_PASSWORD: germancitoquerido
      MYSQL_DATABASE: coderhouse_gamers
      MYSQL_ROOT_PASSWORD: germancitoquerido
    ports:
      - 3309:3306
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: